### ISSUE TITLE
Library build issue

### ISSUE THREAD

**Issue by varunsavaliya** [jamesbrobb/ngx-lightweight-charts#1]
Good to see your library implementation, it's beneficial for my project, especially syncing of the multiple charts.
But there is one issue which is making the library hard to use.

**Issue:** When installing the library using the `npm`, we cannot import the components, methods, and providers as there might be some problem in the build. We are able to solve the problem by building the library and using its build in our node modules but that's not a feasible solution.

Looking forward to getting the solution.

**Comment by jamesbrobb** [comment]
Apologises, and thanks for bringing this to my attention.

In my rush to publish a release version of this, i forgot to update my npm script (to the same version i was using to publish the beta versions) so inadvertently published the actual code instead of the build.

This is now fixed in the latest version.
